items:
- uid: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
  id: _application_gateway_backend_address_pool_inner
  parent: com.microsoft.azure.management.network.implementation
  children:
  - com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.backendAddresses()
  - com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.backendIPConfigurations()
  - com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.etag()
  - com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.name()
  - com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.provisioningState()
  - com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.withBackendAddresses(List< ApplicationGatewayBackendAddress >)
  - com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.withBackendIPConfigurations(List< NetworkInterfaceIPConfigurationInner >)
  - com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.withEtag(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.withName(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.withProvisioningState(String)
  href: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.yml
  langs:
  - java
  name: ApplicationGatewayBackendAddressPoolInner
  fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewayBackendAddressPoolInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayBackendAddressPoolInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayBackendAddressPoolInner.java
    startLine: 20
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>

      <xref href="com.microsoft.azure.management.network._backend" data-throw-if-not-resolved="false"></xref> Address Pool of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewayBackendAddressPoolInner
  inheritance:
  - java.lang.Object
  - SubResource
- uid: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.backendAddresses()
  id: backendAddresses()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.yml
  langs:
  - java
  name: backendAddresses()
  fullName: List<ApplicationGatewayBackendAddress> com.microsoft.azure.management.network.implementation.ApplicationGatewayBackendAddressPoolInner.backendAddresses()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayBackendAddressPoolInner.java
    startLine: 76
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the backendAddresses value.</p>

    <p></p>
  syntax:
    content: public List< ApplicationGatewayBackendAddress > backendAddresses()
    return:
      type: f6a6204dcom.microsoft.azure.management.network._application_gateway_backend_address9ec3e006
      description: <p>the backendAddresses value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.backendIPConfigurations()
  id: backendIPConfigurations()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.yml
  langs:
  - java
  name: backendIPConfigurations()
  fullName: List<NetworkInterfaceIPConfigurationInner> com.microsoft.azure.management.network.implementation.ApplicationGatewayBackendAddressPoolInner.backendIPConfigurations()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayBackendAddressPoolInner.java
    startLine: 56
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the backendIPConfigurations value.</p>

    <p></p>
  syntax:
    content: public List< NetworkInterfaceIPConfigurationInner > backendIPConfigurations()
    return:
      type: f6a6204dcom.microsoft.azure.management.network.implementation._network_interface_i_p_configuration_inner9ec3e006
      description: <p>the backendIPConfigurations value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.etag()
  id: etag()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.yml
  langs:
  - java
  name: etag()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayBackendAddressPoolInner.etag()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayBackendAddressPoolInner.java
    startLine: 136
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the etag value.</p>

    <p></p>
  syntax:
    content: public String etag()
    return:
      type: "26831127"
      description: <p>the etag value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.name()
  id: name()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayBackendAddressPoolInner.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayBackendAddressPoolInner.java
    startLine: 116
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.provisioningState()
  id: provisioningState()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.yml
  langs:
  - java
  name: provisioningState()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayBackendAddressPoolInner.provisioningState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayBackendAddressPoolInner.java
    startLine: 96
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the provisioningState value.</p>

    <p></p>
  syntax:
    content: public String provisioningState()
    return:
      type: "26831127"
      description: <p>the provisioningState value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.withBackendAddresses(List< ApplicationGatewayBackendAddress >)
  id: withBackendAddresses(List< ApplicationGatewayBackendAddress >)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.yml
  langs:
  - java
  name: withBackendAddresses(List< ApplicationGatewayBackendAddress > backendAddresses)
  fullName: ApplicationGatewayBackendAddressPoolInner com.microsoft.azure.management.network.implementation.ApplicationGatewayBackendAddressPoolInner.withBackendAddresses(List< ApplicationGatewayBackendAddress > backendAddresses)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayBackendAddressPoolInner.java
    startLine: 86
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the backendAddresses value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayBackendAddressPoolInner withBackendAddresses(List< ApplicationGatewayBackendAddress > backendAddresses)
    parameters:
    - id: backendAddresses
      type: f6a6204dcom.microsoft.azure.management.network._application_gateway_backend_address9ec3e006
      description: <p>the backendAddresses value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.withBackendIPConfigurations(List< NetworkInterfaceIPConfigurationInner >)
  id: withBackendIPConfigurations(List< NetworkInterfaceIPConfigurationInner >)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.yml
  langs:
  - java
  name: withBackendIPConfigurations(List< NetworkInterfaceIPConfigurationInner > backendIPConfigurations)
  fullName: ApplicationGatewayBackendAddressPoolInner com.microsoft.azure.management.network.implementation.ApplicationGatewayBackendAddressPoolInner.withBackendIPConfigurations(List< NetworkInterfaceIPConfigurationInner > backendIPConfigurations)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayBackendAddressPoolInner.java
    startLine: 66
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the backendIPConfigurations value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayBackendAddressPoolInner withBackendIPConfigurations(List< NetworkInterfaceIPConfigurationInner > backendIPConfigurations)
    parameters:
    - id: backendIPConfigurations
      type: f6a6204dcom.microsoft.azure.management.network.implementation._network_interface_i_p_configuration_inner9ec3e006
      description: <p>the backendIPConfigurations value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.withEtag(String)
  id: withEtag(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.yml
  langs:
  - java
  name: withEtag(String etag)
  fullName: ApplicationGatewayBackendAddressPoolInner com.microsoft.azure.management.network.implementation.ApplicationGatewayBackendAddressPoolInner.withEtag(String etag)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayBackendAddressPoolInner.java
    startLine: 146
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the etag value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayBackendAddressPoolInner withEtag(String etag)
    parameters:
    - id: etag
      type: "26831127"
      description: <p>the etag value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.withName(String)
  id: withName(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.yml
  langs:
  - java
  name: withName(String name)
  fullName: ApplicationGatewayBackendAddressPoolInner com.microsoft.azure.management.network.implementation.ApplicationGatewayBackendAddressPoolInner.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayBackendAddressPoolInner.java
    startLine: 126
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayBackendAddressPoolInner withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.withProvisioningState(String)
  id: withProvisioningState(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.yml
  langs:
  - java
  name: withProvisioningState(String provisioningState)
  fullName: ApplicationGatewayBackendAddressPoolInner com.microsoft.azure.management.network.implementation.ApplicationGatewayBackendAddressPoolInner.withProvisioningState(String provisioningState)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayBackendAddressPoolInner.java
    startLine: 106
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the provisioningState value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayBackendAddressPoolInner withProvisioningState(String provisioningState)
    parameters:
    - id: provisioningState
      type: "26831127"
      description: <p>the provisioningState value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f6a6204dcom.microsoft.azure.management.network.implementation._network_interface_i_p_configuration_inner9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.network.implementation._network_interface_i_p_configuration_inner
    name: NetworkInterfaceIPConfigurationInner
    fullName: com.microsoft.azure.management.network.implementation.NetworkInterfaceIPConfigurationInner
    href: com.microsoft.azure.management.network.implementation._network_interface_i_p_configuration_inner.yml
  - name: " >"
    fullName: " >"
- uid: f6a6204dcom.microsoft.azure.management.network._application_gateway_backend_address9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.network._application_gateway_backend_address
    name: ApplicationGatewayBackendAddress
    fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendAddress
    href: com.microsoft.azure.management.network._application_gateway_backend_address.yml
  - name: " >"
    fullName: " >"
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network.implementation._network_interface_i_p_configuration_inner
  parent: com.microsoft.azure.management.network.implementation
  href: com.microsoft.azure.management.network.implementation._network_interface_i_p_configuration_inner.yml
  name: NetworkInterfaceIPConfigurationInner
  fullName: com.microsoft.azure.management.network.implementation.NetworkInterfaceIPConfigurationInner
  type: Class
  summary: <p>IPConfiguration in a <xref href="com.microsoft.azure.management.network._network_interface" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class NetworkInterfaceIPConfigurationInner
- uid: com.microsoft.azure.management.network._application_gateway_backend_address
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._application_gateway_backend_address.yml
  name: ApplicationGatewayBackendAddress
  fullName: com.microsoft.azure.management.network.ApplicationGatewayBackendAddress
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.azure.management.network._backend" data-throw-if-not-resolved="false"></xref> Address of application gateway. </p>
  syntax:
    content: public class ApplicationGatewayBackendAddress
- uid: com.microsoft.azure.management.network._backend
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._backend.yml
  name: Backend
  fullName: com.microsoft.azure.management.network.Backend
  type: Interface
  summary: <p>An immutable client-side representation of an load balancer's backend address pool. </p>
  syntax:
    content: public interface Backend
- uid: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner
  parent: com.microsoft.azure.management.network.implementation
  href: com.microsoft.azure.management.network.implementation._application_gateway_backend_address_pool_inner.yml
  name: ApplicationGatewayBackendAddressPoolInner
  fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewayBackendAddressPoolInner
  type: Class
  summary: >-
    <p>

      <xref href="com.microsoft.azure.management.network._backend" data-throw-if-not-resolved="false"></xref> Address Pool of application gateway. </p>
  syntax: *o1
