items:
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  id: _slot_config_names_resource_inner
  parent: com.microsoft.azure.management.website.implementation
  children:
  - com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.appSettingNames()
  - com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.connectionStringNames()
  - com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.withAppSettingNames(List< String >)
  - com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.withConnectionStringNames(List< String >)
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  langs:
  - java
  name: SlotConfigNamesResourceInner
  fullName: com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
    startLine: 19
  package: com.microsoft.azure.management.website.implementation
  summary: <p>Slot Config names azure resource. </p>
  syntax: &o1
    content: public class SlotConfigNamesResourceInner
  inheritance:
  - java.lang.Object
  - Resource
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.appSettingNames()
  id: appSettingNames()
  parent: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  langs:
  - java
  name: appSettingNames()
  fullName: List<String> com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner.appSettingNames()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
    startLine: 57
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the appSettingNames value.</p>

    <p></p>
  syntax:
    content: public List< String > appSettingNames()
    return:
      type: f35af49b
      description: <p>the appSettingNames value </p>
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.connectionStringNames()
  id: connectionStringNames()
  parent: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  langs:
  - java
  name: connectionStringNames()
  fullName: List<String> com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner.connectionStringNames()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
    startLine: 37
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Get the connectionStringNames value.</p>

    <p></p>
  syntax:
    content: public List< String > connectionStringNames()
    return:
      type: f35af49b
      description: <p>the connectionStringNames value </p>
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.withAppSettingNames(List< String >)
  id: withAppSettingNames(List< String >)
  parent: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  langs:
  - java
  name: withAppSettingNames(List< String > appSettingNames)
  fullName: SlotConfigNamesResourceInner com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner.withAppSettingNames(List< String > appSettingNames)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
    startLine: 67
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the appSettingNames value.</p>

    <p></p>
  syntax:
    content: public SlotConfigNamesResourceInner withAppSettingNames(List< String > appSettingNames)
    parameters:
    - id: appSettingNames
      type: f35af49b
      description: <p>the appSettingNames value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.withConnectionStringNames(List< String >)
  id: withConnectionStringNames(List< String >)
  parent: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  langs:
  - java
  name: withConnectionStringNames(List< String > connectionStringNames)
  fullName: SlotConfigNamesResourceInner com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner.withConnectionStringNames(List< String > connectionStringNames)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-website/src/main/java/com/microsoft/azure/management/website/implementation/SlotConfigNamesResourceInner.java
    startLine: 47
  package: com.microsoft.azure.management.website.implementation
  summary: >-
    <p>Set the connectionStringNames value.</p>

    <p></p>
  syntax:
    content: public SlotConfigNamesResourceInner withConnectionStringNames(List< String > connectionStringNames)
    parameters:
    - id: connectionStringNames
      type: f35af49b
      description: <p>the connectionStringNames value to set </p>
    return:
      type: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
      description: <p>the <xref href="com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: f35af49b
  spec.java:
  - name: List< String >
    fullName: List< String >
- uid: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner
  parent: com.microsoft.azure.management.website.implementation
  href: com.microsoft.azure.management.website.implementation._slot_config_names_resource_inner.yml
  name: SlotConfigNamesResourceInner
  fullName: com.microsoft.azure.management.website.implementation.SlotConfigNamesResourceInner
  type: Class
  summary: <p>Slot Config names azure resource. </p>
  syntax: *o1
