items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e
  id: _update_ac39f7ab2f23f0c3db8049ad3667081e
  parent: com.microsoft.azure.management.network
  children:
  - com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e.withPrivateIpVersion(IPVersion)
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e.yml
  langs:
  - java
  name: NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 281
  package: com.microsoft.azure.management.network
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to specify private IP address within a virtual network subnet.</p>

    <p></p>
  syntax:
    content: public interface WithPrivateIp<ParentT> extends HasPrivateIpAddress.UpdateDefinitionStages.WithPrivateIpAddress< WithAttach< ParentT > >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressDynamic()
  - com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressStatic(String)
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e.withPrivateIpVersion(IPVersion)
  id: withPrivateIpVersion(IPVersion)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_ac39f7ab2f23f0c3db8049ad3667081e.yml
  langs:
  - java
  name: withPrivateIpVersion(IPVersion ipVersion)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp< ParentT >.withPrivateIpVersion(IPVersion ipVersion)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 287
  package: com.microsoft.azure.management.network
  summary: <p>Specifies the IP version for the private IP address. </p>
  syntax:
    content: public WithAttach< ParentT > withPrivateIpVersion(IPVersion ipVersion)
    parameters:
    - id: ipVersion
      type: com.microsoft.azure.management.network._i_p_version
      description: <p>an IP version </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._update_b03bb382568b5bfa54cd6309635c9089a6da57ba
      description: <p>the next stage of the definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_b03bb382568b5bfa54cd6309635c9089a6da57ba
  spec.java:
  - uid: com.microsoft.azure.management.network._nic_ip_configuration._update_b03bb382568b5bfa54cd6309635c9089
    name: NicIpConfiguration.UpdateDefinitionStages.WithAttach
    fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithAttach
    href: com.microsoft.azure.management.network._nic_ip_configuration._update_b03bb382568b5bfa54cd6309635c9089.yml
  - name: < ParentT >
    fullName: < ParentT >
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressDynamic()
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9
  href: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.yml
  name: withPrivateIpAddressDynamic()
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateDefinitionStages.WithPrivateIpAddress< ReturnT >.withPrivateIpAddressDynamic()
  type: Method
  summary: <p>Enables dynamic private IP address allocation within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressDynamic()
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.withPrivateIpAddressStatic(String)
  parent: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9
  href: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.yml
  name: withPrivateIpAddressStatic(String ipAddress)
  fullName: ReturnT com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateDefinitionStages.WithPrivateIpAddress< ReturnT >.withPrivateIpAddressStatic(String ipAddress)
  type: Method
  summary: <p>Assigns the specified static private IP address within the associated subnet. </p>
  syntax:
    content: public ReturnT withPrivateIpAddressStatic(String ipAddress)
    parameters:
    - id: ipAddress
      type: "26831127"
      description: <p>a static IP address within the associated private IP range </p>
    return:
      type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9
  parent: com.microsoft.azure.management.network.model
  href: com.microsoft.azure.management.network.model._has_private_ip_address_c8d4ab2effc310704b02970a92fdd2e9.yml
  name: HasPrivateIpAddress.UpdateDefinitionStages.WithPrivateIpAddress<ReturnT>
  fullName: com.microsoft.azure.management.network.model.HasPrivateIpAddress.UpdateDefinitionStages.WithPrivateIpAddress<ReturnT>
  type: Interface
  summary: <p>The stage of a definition allowing to specify the private IP address. </p>
  syntax:
    content: public interface WithPrivateIpAddress<ReturnT>
    typeParameters:
    - type: c1a5ebc4
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_definition.yml
  name: NicIpConfiguration.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinition<ParentT>
  type: Interface
  summary: <p>The entirety of a network interface IP configuration definition as part of a network interface update. </p>
  syntax:
    content: public interface UpdateDefinition<ParentT> extends NicIpConfiguration.UpdateDefinitionStages.Blank< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithAttach< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithNetwork< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithPrivateIp< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithSubnet< ParentT >,NicIpConfiguration.UpdateDefinitionStages.WithPublicIpAddress< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._update_b03bb382568b5bfa54cd6309635c9089
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._update_b03bb382568b5bfa54cd6309635c9089.yml
  name: NicIpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: >-
    <p>The final stage of network interface IP configuration. </p>

    <p>At this stage, any remaining optional settings can be specified, or the network interface IP configuration definition can be attached to the parent network interface definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_update.attach()" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable< ParentT >.InUpdate,NicIpConfiguration.UpdateDefinitionStages.WithPublicIpAddress< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._i_p_version
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._i_p_version.yml
  name: IPVersion
  fullName: com.microsoft.azure.management.network.IPVersion
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._i_p_version" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class IPVersion
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable< ParentT >.attach()
  type: Method
  summary: <p>Attaches this child object's definition to its parent's definition. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent object's definition </p>
