items:
- uid: com.microsoft.azure.management.batch.implementation._application_inner
  id: _application_inner
  parent: com.microsoft.azure.management.batch.implementation
  children:
  - com.microsoft.azure.management.batch.implementation._application_inner.allowUpdates()
  - com.microsoft.azure.management.batch.implementation._application_inner.defaultVersion()
  - com.microsoft.azure.management.batch.implementation._application_inner.displayName()
  - com.microsoft.azure.management.batch.implementation._application_inner.id()
  - com.microsoft.azure.management.batch.implementation._application_inner.packages()
  - com.microsoft.azure.management.batch.implementation._application_inner.withAllowUpdates(Boolean)
  - com.microsoft.azure.management.batch.implementation._application_inner.withDefaultVersion(String)
  - com.microsoft.azure.management.batch.implementation._application_inner.withDisplayName(String)
  - com.microsoft.azure.management.batch.implementation._application_inner.withId(String)
  - com.microsoft.azure.management.batch.implementation._application_inner.withPackages(List< ApplicationPackageInner >)
  href: com.microsoft.azure.management.batch.implementation._application_inner.yml
  langs:
  - java
  name: ApplicationInner
  fullName: com.microsoft.azure.management.batch.implementation.ApplicationInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationInner.java
    startLine: 15
  package: com.microsoft.azure.management.batch.implementation
  summary: <p>Contains information about an application in a Batch account. </p>
  syntax: &o1
    content: public class ApplicationInner
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.batch.implementation._application_inner.allowUpdates()
  id: allowUpdates()
  parent: com.microsoft.azure.management.batch.implementation._application_inner
  href: com.microsoft.azure.management.batch.implementation._application_inner.yml
  langs:
  - java
  name: allowUpdates()
  fullName: Boolean com.microsoft.azure.management.batch.implementation.ApplicationInner.allowUpdates()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationInner.java
    startLine: 108
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Get the allowUpdates value.</p>

    <p></p>
  syntax:
    content: public Boolean allowUpdates()
    return:
      type: 866c2227
      description: <p>the allowUpdates value </p>
- uid: com.microsoft.azure.management.batch.implementation._application_inner.defaultVersion()
  id: defaultVersion()
  parent: com.microsoft.azure.management.batch.implementation._application_inner
  href: com.microsoft.azure.management.batch.implementation._application_inner.yml
  langs:
  - java
  name: defaultVersion()
  fullName: String com.microsoft.azure.management.batch.implementation.ApplicationInner.defaultVersion()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationInner.java
    startLine: 128
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Get the defaultVersion value.</p>

    <p></p>
  syntax:
    content: public String defaultVersion()
    return:
      type: "26831127"
      description: <p>the defaultVersion value </p>
- uid: com.microsoft.azure.management.batch.implementation._application_inner.displayName()
  id: displayName()
  parent: com.microsoft.azure.management.batch.implementation._application_inner
  href: com.microsoft.azure.management.batch.implementation._application_inner.yml
  langs:
  - java
  name: displayName()
  fullName: String com.microsoft.azure.management.batch.implementation.ApplicationInner.displayName()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationInner.java
    startLine: 68
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Get the displayName value.</p>

    <p></p>
  syntax:
    content: public String displayName()
    return:
      type: "26831127"
      description: <p>the displayName value </p>
- uid: com.microsoft.azure.management.batch.implementation._application_inner.id()
  id: id()
  parent: com.microsoft.azure.management.batch.implementation._application_inner
  href: com.microsoft.azure.management.batch.implementation._application_inner.yml
  langs:
  - java
  name: id()
  fullName: String com.microsoft.azure.management.batch.implementation.ApplicationInner.id()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationInner.java
    startLine: 48
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Get the id value.</p>

    <p></p>
  syntax:
    content: public String id()
    return:
      type: "26831127"
      description: <p>the id value </p>
- uid: com.microsoft.azure.management.batch.implementation._application_inner.packages()
  id: packages()
  parent: com.microsoft.azure.management.batch.implementation._application_inner
  href: com.microsoft.azure.management.batch.implementation._application_inner.yml
  langs:
  - java
  name: packages()
  fullName: List<ApplicationPackageInner> com.microsoft.azure.management.batch.implementation.ApplicationInner.packages()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationInner.java
    startLine: 88
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Get the packages value.</p>

    <p></p>
  syntax:
    content: public List< ApplicationPackageInner > packages()
    return:
      type: f6a6204dcom.microsoft.azure.management.batch.implementation._application_package_inner9ec3e006
      description: <p>the packages value </p>
- uid: com.microsoft.azure.management.batch.implementation._application_inner.withAllowUpdates(Boolean)
  id: withAllowUpdates(Boolean)
  parent: com.microsoft.azure.management.batch.implementation._application_inner
  href: com.microsoft.azure.management.batch.implementation._application_inner.yml
  langs:
  - java
  name: withAllowUpdates(Boolean allowUpdates)
  fullName: ApplicationInner com.microsoft.azure.management.batch.implementation.ApplicationInner.withAllowUpdates(Boolean allowUpdates)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationInner.java
    startLine: 118
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Set the allowUpdates value.</p>

    <p></p>
  syntax:
    content: public ApplicationInner withAllowUpdates(Boolean allowUpdates)
    parameters:
    - id: allowUpdates
      type: 866c2227
      description: <p>the allowUpdates value to set </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._application_inner
      description: <p>the <xref href="com.microsoft.azure.management.batch.implementation._application_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.batch.implementation._application_inner.withDefaultVersion(String)
  id: withDefaultVersion(String)
  parent: com.microsoft.azure.management.batch.implementation._application_inner
  href: com.microsoft.azure.management.batch.implementation._application_inner.yml
  langs:
  - java
  name: withDefaultVersion(String defaultVersion)
  fullName: ApplicationInner com.microsoft.azure.management.batch.implementation.ApplicationInner.withDefaultVersion(String defaultVersion)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationInner.java
    startLine: 138
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Set the defaultVersion value.</p>

    <p></p>
  syntax:
    content: public ApplicationInner withDefaultVersion(String defaultVersion)
    parameters:
    - id: defaultVersion
      type: "26831127"
      description: <p>the defaultVersion value to set </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._application_inner
      description: <p>the <xref href="com.microsoft.azure.management.batch.implementation._application_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.batch.implementation._application_inner.withDisplayName(String)
  id: withDisplayName(String)
  parent: com.microsoft.azure.management.batch.implementation._application_inner
  href: com.microsoft.azure.management.batch.implementation._application_inner.yml
  langs:
  - java
  name: withDisplayName(String displayName)
  fullName: ApplicationInner com.microsoft.azure.management.batch.implementation.ApplicationInner.withDisplayName(String displayName)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationInner.java
    startLine: 78
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Set the displayName value.</p>

    <p></p>
  syntax:
    content: public ApplicationInner withDisplayName(String displayName)
    parameters:
    - id: displayName
      type: "26831127"
      description: <p>the displayName value to set </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._application_inner
      description: <p>the <xref href="com.microsoft.azure.management.batch.implementation._application_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.batch.implementation._application_inner.withId(String)
  id: withId(String)
  parent: com.microsoft.azure.management.batch.implementation._application_inner
  href: com.microsoft.azure.management.batch.implementation._application_inner.yml
  langs:
  - java
  name: withId(String id)
  fullName: ApplicationInner com.microsoft.azure.management.batch.implementation.ApplicationInner.withId(String id)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationInner.java
    startLine: 58
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Set the id value.</p>

    <p></p>
  syntax:
    content: public ApplicationInner withId(String id)
    parameters:
    - id: id
      type: "26831127"
      description: <p>the id value to set </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._application_inner
      description: <p>the <xref href="com.microsoft.azure.management.batch.implementation._application_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.batch.implementation._application_inner.withPackages(List< ApplicationPackageInner >)
  id: withPackages(List< ApplicationPackageInner >)
  parent: com.microsoft.azure.management.batch.implementation._application_inner
  href: com.microsoft.azure.management.batch.implementation._application_inner.yml
  langs:
  - java
  name: withPackages(List< ApplicationPackageInner > packages)
  fullName: ApplicationInner com.microsoft.azure.management.batch.implementation.ApplicationInner.withPackages(List< ApplicationPackageInner > packages)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationInner.java
    startLine: 98
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Set the packages value.</p>

    <p></p>
  syntax:
    content: public ApplicationInner withPackages(List< ApplicationPackageInner > packages)
    parameters:
    - id: packages
      type: f6a6204dcom.microsoft.azure.management.batch.implementation._application_package_inner9ec3e006
      description: <p>the packages value to set </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._application_inner
      description: <p>the <xref href="com.microsoft.azure.management.batch.implementation._application_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: f6a6204dcom.microsoft.azure.management.batch.implementation._application_package_inner9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.batch.implementation._application_package_inner
    name: ApplicationPackageInner
    fullName: com.microsoft.azure.management.batch.implementation.ApplicationPackageInner
    href: com.microsoft.azure.management.batch.implementation._application_package_inner.yml
  - name: " >"
    fullName: " >"
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: com.microsoft.azure.management.batch.implementation._application_package_inner
  parent: com.microsoft.azure.management.batch.implementation
  href: com.microsoft.azure.management.batch.implementation._application_package_inner.yml
  name: ApplicationPackageInner
  fullName: com.microsoft.azure.management.batch.implementation.ApplicationPackageInner
  type: Class
  summary: <p>An application package which represents a particular version of an application. </p>
  syntax:
    content: public class ApplicationPackageInner
- uid: com.microsoft.azure.management.batch.implementation._application_inner
  parent: com.microsoft.azure.management.batch.implementation
  href: com.microsoft.azure.management.batch.implementation._application_inner.yml
  name: ApplicationInner
  fullName: com.microsoft.azure.management.batch.implementation.ApplicationInner
  type: Class
  summary: <p>Contains information about an application in a Batch account. </p>
  syntax: *o1
