items:
- uid: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
  id: _virtual_network_gateway_i_p_configuration_inner
  parent: com.microsoft.azure.management.network.implementation
  children:
  - com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.etag()
  - com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.name()
  - com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.privateIPAllocationMethod()
  - com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.provisioningState()
  - com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.publicIPAddress()
  - com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.subnet()
  - com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.withEtag(String)
  - com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.withName(String)
  - com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.withPrivateIPAllocationMethod(IPAllocationMethod)
  - com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.withProvisioningState(String)
  - com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.withPublicIPAddress(SubResource)
  - com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.withSubnet(SubResource)
  href: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: VirtualNetworkGatewayIPConfigurationInner
  fullName: com.microsoft.azure.management.network.implementation.VirtualNetworkGatewayIPConfigurationInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/VirtualNetworkGatewayIPConfigurationInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/VirtualNetworkGatewayIPConfigurationInner.java
    startLine: 19
  package: com.microsoft.azure.management.network.implementation
  summary: <p>IpConfiguration for Virtual network gateway. </p>
  syntax: &o1
    content: public class VirtualNetworkGatewayIPConfigurationInner
  inheritance:
  - java.lang.Object
  - SubResource
- uid: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.etag()
  id: etag()
  parent: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: etag()
  fullName: String com.microsoft.azure.management.network.implementation.VirtualNetworkGatewayIPConfigurationInner.etag()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/VirtualNetworkGatewayIPConfigurationInner.java
    startLine: 162
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the etag value.</p>

    <p></p>
  syntax:
    content: public String etag()
    return:
      type: "26831127"
      description: <p>the etag value </p>
- uid: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.name()
  id: name()
  parent: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.network.implementation.VirtualNetworkGatewayIPConfigurationInner.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/VirtualNetworkGatewayIPConfigurationInner.java
    startLine: 142
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.privateIPAllocationMethod()
  id: privateIPAllocationMethod()
  parent: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: privateIPAllocationMethod()
  fullName: IPAllocationMethod com.microsoft.azure.management.network.implementation.VirtualNetworkGatewayIPConfigurationInner.privateIPAllocationMethod()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/VirtualNetworkGatewayIPConfigurationInner.java
    startLine: 62
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the privateIPAllocationMethod value.</p>

    <p></p>
  syntax:
    content: public IPAllocationMethod privateIPAllocationMethod()
    return:
      type: com.microsoft.azure.management.network._i_p_allocation_method
      description: <p>the privateIPAllocationMethod value </p>
- uid: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.provisioningState()
  id: provisioningState()
  parent: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: provisioningState()
  fullName: String com.microsoft.azure.management.network.implementation.VirtualNetworkGatewayIPConfigurationInner.provisioningState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/VirtualNetworkGatewayIPConfigurationInner.java
    startLine: 122
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the provisioningState value.</p>

    <p></p>
  syntax:
    content: public String provisioningState()
    return:
      type: "26831127"
      description: <p>the provisioningState value </p>
- uid: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.publicIPAddress()
  id: publicIPAddress()
  parent: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: publicIPAddress()
  fullName: SubResource com.microsoft.azure.management.network.implementation.VirtualNetworkGatewayIPConfigurationInner.publicIPAddress()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/VirtualNetworkGatewayIPConfigurationInner.java
    startLine: 102
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the publicIPAddress value.</p>

    <p></p>
  syntax:
    content: public SubResource publicIPAddress()
    return:
      type: 4151c390
      description: <p>the publicIPAddress value </p>
- uid: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.subnet()
  id: subnet()
  parent: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: subnet()
  fullName: SubResource com.microsoft.azure.management.network.implementation.VirtualNetworkGatewayIPConfigurationInner.subnet()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/VirtualNetworkGatewayIPConfigurationInner.java
    startLine: 82
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the subnet value.</p>

    <p></p>
  syntax:
    content: public SubResource subnet()
    return:
      type: 4151c390
      description: <p>the subnet value </p>
- uid: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.withEtag(String)
  id: withEtag(String)
  parent: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: withEtag(String etag)
  fullName: VirtualNetworkGatewayIPConfigurationInner com.microsoft.azure.management.network.implementation.VirtualNetworkGatewayIPConfigurationInner.withEtag(String etag)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/VirtualNetworkGatewayIPConfigurationInner.java
    startLine: 172
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the etag value.</p>

    <p></p>
  syntax:
    content: public VirtualNetworkGatewayIPConfigurationInner withEtag(String etag)
    parameters:
    - id: etag
      type: "26831127"
      description: <p>the etag value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.withName(String)
  id: withName(String)
  parent: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: withName(String name)
  fullName: VirtualNetworkGatewayIPConfigurationInner com.microsoft.azure.management.network.implementation.VirtualNetworkGatewayIPConfigurationInner.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/VirtualNetworkGatewayIPConfigurationInner.java
    startLine: 152
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public VirtualNetworkGatewayIPConfigurationInner withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.withPrivateIPAllocationMethod(IPAllocationMethod)
  id: withPrivateIPAllocationMethod(IPAllocationMethod)
  parent: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: withPrivateIPAllocationMethod(IPAllocationMethod privateIPAllocationMethod)
  fullName: VirtualNetworkGatewayIPConfigurationInner com.microsoft.azure.management.network.implementation.VirtualNetworkGatewayIPConfigurationInner.withPrivateIPAllocationMethod(IPAllocationMethod privateIPAllocationMethod)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/VirtualNetworkGatewayIPConfigurationInner.java
    startLine: 72
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the privateIPAllocationMethod value.</p>

    <p></p>
  syntax:
    content: public VirtualNetworkGatewayIPConfigurationInner withPrivateIPAllocationMethod(IPAllocationMethod privateIPAllocationMethod)
    parameters:
    - id: privateIPAllocationMethod
      type: com.microsoft.azure.management.network._i_p_allocation_method
      description: <p>the privateIPAllocationMethod value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.withProvisioningState(String)
  id: withProvisioningState(String)
  parent: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: withProvisioningState(String provisioningState)
  fullName: VirtualNetworkGatewayIPConfigurationInner com.microsoft.azure.management.network.implementation.VirtualNetworkGatewayIPConfigurationInner.withProvisioningState(String provisioningState)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/VirtualNetworkGatewayIPConfigurationInner.java
    startLine: 132
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the provisioningState value.</p>

    <p></p>
  syntax:
    content: public VirtualNetworkGatewayIPConfigurationInner withProvisioningState(String provisioningState)
    parameters:
    - id: provisioningState
      type: "26831127"
      description: <p>the provisioningState value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.withPublicIPAddress(SubResource)
  id: withPublicIPAddress(SubResource)
  parent: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: withPublicIPAddress(SubResource publicIPAddress)
  fullName: VirtualNetworkGatewayIPConfigurationInner com.microsoft.azure.management.network.implementation.VirtualNetworkGatewayIPConfigurationInner.withPublicIPAddress(SubResource publicIPAddress)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/VirtualNetworkGatewayIPConfigurationInner.java
    startLine: 112
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the publicIPAddress value.</p>

    <p></p>
  syntax:
    content: public VirtualNetworkGatewayIPConfigurationInner withPublicIPAddress(SubResource publicIPAddress)
    parameters:
    - id: publicIPAddress
      type: 4151c390
      description: <p>the publicIPAddress value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.withSubnet(SubResource)
  id: withSubnet(SubResource)
  parent: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
  href: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.yml
  langs:
  - java
  name: withSubnet(SubResource subnet)
  fullName: VirtualNetworkGatewayIPConfigurationInner com.microsoft.azure.management.network.implementation.VirtualNetworkGatewayIPConfigurationInner.withSubnet(SubResource subnet)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/VirtualNetworkGatewayIPConfigurationInner.java
    startLine: 92
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the subnet value.</p>

    <p></p>
  syntax:
    content: public VirtualNetworkGatewayIPConfigurationInner withSubnet(SubResource subnet)
    parameters:
    - id: subnet
      type: 4151c390
      description: <p>the subnet value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 4151c390
  spec.java:
  - name: SubResource
    fullName: SubResource
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network._i_p_allocation_method
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._i_p_allocation_method.yml
  name: IPAllocationMethod
  fullName: com.microsoft.azure.management.network.IPAllocationMethod
  type: Class
  summary: <p>Defines values for <xref href="com.microsoft.azure.management.network._i_p_allocation_method" data-throw-if-not-resolved="false"></xref>. </p>
  syntax:
    content: public class IPAllocationMethod
- uid: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner
  parent: com.microsoft.azure.management.network.implementation
  href: com.microsoft.azure.management.network.implementation._virtual_network_gateway_i_p_configuration_inner.yml
  name: VirtualNetworkGatewayIPConfigurationInner
  fullName: com.microsoft.azure.management.network.implementation.VirtualNetworkGatewayIPConfigurationInner
  type: Class
  summary: <p>IpConfiguration for Virtual network gateway. </p>
  syntax: *o1
