items:
- uid: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
  id: _application_gateway_ssl_certificate_inner
  parent: com.microsoft.azure.management.network.implementation
  children:
  - com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.data()
  - com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.etag()
  - com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.name()
  - com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.password()
  - com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.provisioningState()
  - com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.publicCertData()
  - com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.withData(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.withEtag(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.withName(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.withPassword(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.withProvisioningState(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.withPublicCertData(String)
  href: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.yml
  langs:
  - java
  name: ApplicationGatewaySslCertificateInner
  fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewaySslCertificateInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewaySslCertificateInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewaySslCertificateInner.java
    startLine: 18
  package: com.microsoft.azure.management.network.implementation
  summary: <p>SSL certificates of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewaySslCertificateInner
  inheritance:
  - java.lang.Object
  - SubResource
- uid: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.data()
  id: data()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.yml
  langs:
  - java
  name: data()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewaySslCertificateInner.data()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewaySslCertificateInner.java
    startLine: 60
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the data value.</p>

    <p></p>
  syntax:
    content: public String data()
    return:
      type: "26831127"
      description: <p>the data value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.etag()
  id: etag()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.yml
  langs:
  - java
  name: etag()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewaySslCertificateInner.etag()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewaySslCertificateInner.java
    startLine: 160
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the etag value.</p>

    <p></p>
  syntax:
    content: public String etag()
    return:
      type: "26831127"
      description: <p>the etag value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.name()
  id: name()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewaySslCertificateInner.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewaySslCertificateInner.java
    startLine: 140
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.password()
  id: password()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.yml
  langs:
  - java
  name: password()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewaySslCertificateInner.password()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewaySslCertificateInner.java
    startLine: 80
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the password value.</p>

    <p></p>
  syntax:
    content: public String password()
    return:
      type: "26831127"
      description: <p>the password value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.provisioningState()
  id: provisioningState()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.yml
  langs:
  - java
  name: provisioningState()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewaySslCertificateInner.provisioningState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewaySslCertificateInner.java
    startLine: 120
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the provisioningState value.</p>

    <p></p>
  syntax:
    content: public String provisioningState()
    return:
      type: "26831127"
      description: <p>the provisioningState value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.publicCertData()
  id: publicCertData()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.yml
  langs:
  - java
  name: publicCertData()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewaySslCertificateInner.publicCertData()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewaySslCertificateInner.java
    startLine: 100
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the publicCertData value.</p>

    <p></p>
  syntax:
    content: public String publicCertData()
    return:
      type: "26831127"
      description: <p>the publicCertData value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.withData(String)
  id: withData(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.yml
  langs:
  - java
  name: withData(String data)
  fullName: ApplicationGatewaySslCertificateInner com.microsoft.azure.management.network.implementation.ApplicationGatewaySslCertificateInner.withData(String data)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewaySslCertificateInner.java
    startLine: 70
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the data value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySslCertificateInner withData(String data)
    parameters:
    - id: data
      type: "26831127"
      description: <p>the data value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.withEtag(String)
  id: withEtag(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.yml
  langs:
  - java
  name: withEtag(String etag)
  fullName: ApplicationGatewaySslCertificateInner com.microsoft.azure.management.network.implementation.ApplicationGatewaySslCertificateInner.withEtag(String etag)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewaySslCertificateInner.java
    startLine: 170
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the etag value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySslCertificateInner withEtag(String etag)
    parameters:
    - id: etag
      type: "26831127"
      description: <p>the etag value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.withName(String)
  id: withName(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.yml
  langs:
  - java
  name: withName(String name)
  fullName: ApplicationGatewaySslCertificateInner com.microsoft.azure.management.network.implementation.ApplicationGatewaySslCertificateInner.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewaySslCertificateInner.java
    startLine: 150
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySslCertificateInner withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.withPassword(String)
  id: withPassword(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.yml
  langs:
  - java
  name: withPassword(String password)
  fullName: ApplicationGatewaySslCertificateInner com.microsoft.azure.management.network.implementation.ApplicationGatewaySslCertificateInner.withPassword(String password)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewaySslCertificateInner.java
    startLine: 90
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the password value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySslCertificateInner withPassword(String password)
    parameters:
    - id: password
      type: "26831127"
      description: <p>the password value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.withProvisioningState(String)
  id: withProvisioningState(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.yml
  langs:
  - java
  name: withProvisioningState(String provisioningState)
  fullName: ApplicationGatewaySslCertificateInner com.microsoft.azure.management.network.implementation.ApplicationGatewaySslCertificateInner.withProvisioningState(String provisioningState)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewaySslCertificateInner.java
    startLine: 130
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the provisioningState value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySslCertificateInner withProvisioningState(String provisioningState)
    parameters:
    - id: provisioningState
      type: "26831127"
      description: <p>the provisioningState value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.withPublicCertData(String)
  id: withPublicCertData(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.yml
  langs:
  - java
  name: withPublicCertData(String publicCertData)
  fullName: ApplicationGatewaySslCertificateInner com.microsoft.azure.management.network.implementation.ApplicationGatewaySslCertificateInner.withPublicCertData(String publicCertData)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewaySslCertificateInner.java
    startLine: 110
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the publicCertData value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewaySslCertificateInner withPublicCertData(String publicCertData)
    parameters:
    - id: publicCertData
      type: "26831127"
      description: <p>the publicCertData value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner
  parent: com.microsoft.azure.management.network.implementation
  href: com.microsoft.azure.management.network.implementation._application_gateway_ssl_certificate_inner.yml
  name: ApplicationGatewaySslCertificateInner
  fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewaySslCertificateInner
  type: Class
  summary: <p>SSL certificates of application gateway. </p>
  syntax: *o1
