items:
- uid: com.microsoft.azure.management.batch._batch_account._update_stages._with_application
  id: _with_application
  parent: com.microsoft.azure.management.batch
  children:
  - com.microsoft.azure.management.batch._batch_account._update_stages._with_application.defineNewApplication(String)
  - com.microsoft.azure.management.batch._batch_account._update_stages._with_application.updateApplication(String)
  - com.microsoft.azure.management.batch._batch_account._update_stages._with_application.withoutApplication(String)
  href: com.microsoft.azure.management.batch._batch_account._update_stages._with_application.yml
  langs:
  - java
  name: BatchAccount.UpdateStages.WithApplication
  fullName: com.microsoft.azure.management.batch.BatchAccount.UpdateStages.WithApplication
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/BatchAccount.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/BatchAccount.java
    startLine: 238
  package: com.microsoft.azure.management.batch
  summary: <p>A batch account definition to allow creation of application. </p>
  syntax:
    content: public interface WithApplication
- uid: com.microsoft.azure.management.batch._batch_account._update_stages._with_application.defineNewApplication(String)
  id: defineNewApplication(String)
  parent: com.microsoft.azure.management.batch._batch_account._update_stages._with_application
  href: com.microsoft.azure.management.batch._batch_account._update_stages._with_application.yml
  langs:
  - java
  name: defineNewApplication(String applicationId)
  fullName: Application.UpdateDefinitionStages.Blank<Update> com.microsoft.azure.management.batch.BatchAccount.UpdateStages.WithApplication.defineNewApplication(String applicationId)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/BatchAccount.java
    startLine: 245
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Specifies definition of an application to be created in a batch account.</p>

    <p></p>
  syntax:
    content: public Application.UpdateDefinitionStages.Blank< Update > defineNewApplication(String applicationId)
    parameters:
    - id: applicationId
      type: "26831127"
      description: <p>the reference name for application </p>
    return:
      type: 2c5e2fdccom.microsoft.azure.management.batch._batch_account._update9ec3e006
      description: <p>the stage representing configuration for the extension </p>
- uid: com.microsoft.azure.management.batch._batch_account._update_stages._with_application.updateApplication(String)
  id: updateApplication(String)
  parent: com.microsoft.azure.management.batch._batch_account._update_stages._with_application
  href: com.microsoft.azure.management.batch._batch_account._update_stages._with_application.yml
  langs:
  - java
  name: updateApplication(String applicationId)
  fullName: Application.Update com.microsoft.azure.management.batch.BatchAccount.UpdateStages.WithApplication.updateApplication(String applicationId)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/BatchAccount.java
    startLine: 253
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Begins the description of an update of an existing application of this batch account.</p>

    <p></p>
  syntax:
    content: public Application.Update updateApplication(String applicationId)
    parameters:
    - id: applicationId
      type: "26831127"
      description: <p>the reference name for the application to be updated </p>
    return:
      type: b1cae572
      description: <p>the stage representing updatable application. </p>
- uid: com.microsoft.azure.management.batch._batch_account._update_stages._with_application.withoutApplication(String)
  id: withoutApplication(String)
  parent: com.microsoft.azure.management.batch._batch_account._update_stages._with_application
  href: com.microsoft.azure.management.batch._batch_account._update_stages._with_application.yml
  langs:
  - java
  name: withoutApplication(String applicationId)
  fullName: Update com.microsoft.azure.management.batch.BatchAccount.UpdateStages.WithApplication.withoutApplication(String applicationId)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/BatchAccount.java
    startLine: 261
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Deletes specified application from the batch account.</p>

    <p></p>
  syntax:
    content: public Update withoutApplication(String applicationId)
    parameters:
    - id: applicationId
      type: "26831127"
      description: <p>the reference name for the application to be removed </p>
    return:
      type: com.microsoft.azure.management.batch._batch_account._update
      description: <p>the stage representing updatable batch account definition. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 2c5e2fdccom.microsoft.azure.management.batch._batch_account._update9ec3e006
  spec.java:
  - name: 'Application.UpdateDefinitionStages.Blank< '
    fullName: 'Application.UpdateDefinitionStages.Blank< '
  - uid: com.microsoft.azure.management.batch._batch_account._update
    name: BatchAccount.Update
    fullName: com.microsoft.azure.management.batch.BatchAccount.Update
    href: com.microsoft.azure.management.batch._batch_account._update.yml
  - name: " >"
    fullName: " >"
- uid: b1cae572
  spec.java:
  - name: Application.Update
    fullName: Application.Update
- uid: com.microsoft.azure.management.batch._batch_account._update
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._batch_account._update.yml
  name: BatchAccount.Update
  fullName: com.microsoft.azure.management.batch.BatchAccount.Update
  type: Interface
  summary: <p>The template for a storage account update operation, containing all the settings that can be modified. </p>
  syntax:
    content: public interface Update extends Appliable< BatchAccount >,Resource.UpdateWithTags< Update >,BatchAccount.UpdateStages.WithStorageAccount,BatchAccount.UpdateStages.WithApplication
- uid: com.microsoft.azure.management.batch.implementation._batch_account_impl.defineNewApplication(String)
  parent: com.microsoft.azure.management.batch.implementation._batch_account_impl
  href: com.microsoft.azure.management.batch.implementation._batch_account_impl.yml
  name: defineNewApplication(String applicationId)
  fullName: ApplicationImpl com.microsoft.azure.management.batch.implementation.BatchAccountImpl.defineNewApplication(String applicationId)
  type: Method
  summary: >-
    <p>First stage to create new application in Batch account.</p>

    <p></p>
  syntax:
    content: public ApplicationImpl defineNewApplication(String applicationId)
    parameters:
    - id: applicationId
      type: "26831127"
      description: <p>id of the application to create </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._application_impl
      description: <p>next stage to create the Batch account. </p>
- uid: com.microsoft.azure.management.batch.implementation._batch_account_impl.updateApplication(String)
  parent: com.microsoft.azure.management.batch.implementation._batch_account_impl
  href: com.microsoft.azure.management.batch.implementation._batch_account_impl.yml
  name: updateApplication(String applicationId)
  fullName: ApplicationImpl com.microsoft.azure.management.batch.implementation.BatchAccountImpl.updateApplication(String applicationId)
  type: Method
  summary: >-
    <p>Begins the description of an update of an existing application of this batch account.</p>

    <p></p>
  syntax:
    content: public ApplicationImpl updateApplication(String applicationId)
    parameters:
    - id: applicationId
      type: "26831127"
      description: <p>the reference name for the application to be updated </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._application_impl
      description: <p>the stage representing updatable application. </p>
- uid: com.microsoft.azure.management.batch.implementation._batch_account_impl.withoutApplication(String)
  parent: com.microsoft.azure.management.batch.implementation._batch_account_impl
  href: com.microsoft.azure.management.batch.implementation._batch_account_impl.yml
  name: withoutApplication(String applicationId)
  fullName: Update com.microsoft.azure.management.batch.implementation.BatchAccountImpl.withoutApplication(String applicationId)
  type: Method
  summary: >-
    <p>Deletes specified application from the batch account.</p>

    <p></p>
  syntax:
    content: public Update withoutApplication(String applicationId)
    parameters:
    - id: applicationId
      type: "26831127"
      description: <p>the reference name for the application to be removed </p>
    return:
      type: com.microsoft.azure.management.batch._batch_account._update
      description: <p>the stage representing updatable batch account definition. </p>
