items:
- uid: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner
  id: _update_application_parameters_inner
  parent: com.microsoft.azure.management.batch.implementation
  children:
  - com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.allowUpdates()
  - com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.defaultVersion()
  - com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.displayName()
  - com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.withAllowUpdates(Boolean)
  - com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.withDefaultVersion(String)
  - com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.withDisplayName(String)
  href: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.yml
  langs:
  - java
  name: UpdateApplicationParametersInner
  fullName: com.microsoft.azure.management.batch.implementation.UpdateApplicationParametersInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/UpdateApplicationParametersInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/UpdateApplicationParametersInner.java
    startLine: 14
  package: com.microsoft.azure.management.batch.implementation
  summary: <p>Parameters for an ApplicationOperations.UpdateApplication request. </p>
  syntax: &o1
    content: public class UpdateApplicationParametersInner
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.allowUpdates()
  id: allowUpdates()
  parent: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner
  href: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.yml
  langs:
  - java
  name: allowUpdates()
  fullName: Boolean com.microsoft.azure.management.batch.implementation.UpdateApplicationParametersInner.allowUpdates()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/UpdateApplicationParametersInner.java
    startLine: 37
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Get the allowUpdates value.</p>

    <p></p>
  syntax:
    content: public Boolean allowUpdates()
    return:
      type: 866c2227
      description: <p>the allowUpdates value </p>
- uid: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.defaultVersion()
  id: defaultVersion()
  parent: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner
  href: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.yml
  langs:
  - java
  name: defaultVersion()
  fullName: String com.microsoft.azure.management.batch.implementation.UpdateApplicationParametersInner.defaultVersion()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/UpdateApplicationParametersInner.java
    startLine: 57
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Get the defaultVersion value.</p>

    <p></p>
  syntax:
    content: public String defaultVersion()
    return:
      type: "26831127"
      description: <p>the defaultVersion value </p>
- uid: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.displayName()
  id: displayName()
  parent: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner
  href: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.yml
  langs:
  - java
  name: displayName()
  fullName: String com.microsoft.azure.management.batch.implementation.UpdateApplicationParametersInner.displayName()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/UpdateApplicationParametersInner.java
    startLine: 77
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Get the displayName value.</p>

    <p></p>
  syntax:
    content: public String displayName()
    return:
      type: "26831127"
      description: <p>the displayName value </p>
- uid: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.withAllowUpdates(Boolean)
  id: withAllowUpdates(Boolean)
  parent: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner
  href: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.yml
  langs:
  - java
  name: withAllowUpdates(Boolean allowUpdates)
  fullName: UpdateApplicationParametersInner com.microsoft.azure.management.batch.implementation.UpdateApplicationParametersInner.withAllowUpdates(Boolean allowUpdates)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/UpdateApplicationParametersInner.java
    startLine: 47
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Set the allowUpdates value.</p>

    <p></p>
  syntax:
    content: public UpdateApplicationParametersInner withAllowUpdates(Boolean allowUpdates)
    parameters:
    - id: allowUpdates
      type: 866c2227
      description: <p>the allowUpdates value to set </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner
      description: <p>the <xref href="com.microsoft.azure.management.batch.implementation._update_application_parameters_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.withDefaultVersion(String)
  id: withDefaultVersion(String)
  parent: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner
  href: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.yml
  langs:
  - java
  name: withDefaultVersion(String defaultVersion)
  fullName: UpdateApplicationParametersInner com.microsoft.azure.management.batch.implementation.UpdateApplicationParametersInner.withDefaultVersion(String defaultVersion)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/UpdateApplicationParametersInner.java
    startLine: 67
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Set the defaultVersion value.</p>

    <p></p>
  syntax:
    content: public UpdateApplicationParametersInner withDefaultVersion(String defaultVersion)
    parameters:
    - id: defaultVersion
      type: "26831127"
      description: <p>the defaultVersion value to set </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner
      description: <p>the <xref href="com.microsoft.azure.management.batch.implementation._update_application_parameters_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.withDisplayName(String)
  id: withDisplayName(String)
  parent: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner
  href: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.yml
  langs:
  - java
  name: withDisplayName(String displayName)
  fullName: UpdateApplicationParametersInner com.microsoft.azure.management.batch.implementation.UpdateApplicationParametersInner.withDisplayName(String displayName)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/UpdateApplicationParametersInner.java
    startLine: 87
  package: com.microsoft.azure.management.batch.implementation
  summary: >-
    <p>Set the displayName value.</p>

    <p></p>
  syntax:
    content: public UpdateApplicationParametersInner withDisplayName(String displayName)
    parameters:
    - id: displayName
      type: "26831127"
      description: <p>the displayName value to set </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner
      description: <p>the <xref href="com.microsoft.azure.management.batch.implementation._update_application_parameters_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner
  parent: com.microsoft.azure.management.batch.implementation
  href: com.microsoft.azure.management.batch.implementation._update_application_parameters_inner.yml
  name: UpdateApplicationParametersInner
  fullName: com.microsoft.azure.management.batch.implementation.UpdateApplicationParametersInner
  type: Class
  summary: <p>Parameters for an ApplicationOperations.UpdateApplication request. </p>
  syntax: *o1
