items:
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_attach
  id: _with_attach
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_attach.yml
  langs:
  - java
  name: NicIpConfiguration.DefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithAttach<ParentT>
  type: Interface
  source:
    remote:
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NicIpConfiguration.java
    startLine: 194
  package: com.microsoft.azure.management.network
  summary: >-
    <p>The final stage of network interface IP configuration. </p>

    <p>At this stage, any remaining optional settings can be specified, or the network interface IP configuration definition can be attached to the parent network interface definition using <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()" data-throw-if-not-resolved="false"></xref>.</p>

    <p></p>
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable< ParentT >.InDefinition,NicIpConfiguration.DefinitionStages.WithPublicIpAddress< ParentT >,NicIpConfiguration.DefinitionStages.WithLoadBalancer< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()
  - com.microsoft.azure.management.network._nic_ip_configuration._definit7752274ae53ec6c93861035156ab069e.withExistingLoadBalancerBackend(LoadBalancer,String)
  - com.microsoft.azure.management.network._nic_ip_configuration._definit7752274ae53ec6c93861035156ab069e.withExistingLoadBalancerInboundNatRule(LoadBalancer,String)
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable< ParentT >.InDefinition< ParentT >.attach()
  type: Method
  summary: <p>Attaches the child definition to the parent resource definiton. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definit7752274ae53ec6c93861035156ab069e.withExistingLoadBalancerBackend(LoadBalancer,String)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._definit7752274ae53ec6c93861035156ab069e
  href: com.microsoft.azure.management.network._nic_ip_configuration._definit7752274ae53ec6c93861035156ab069e.yml
  name: withExistingLoadBalancerBackend(LoadBalancer loadBalancer, String backendName)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithLoadBalancer< ParentT >.withExistingLoadBalancerBackend(LoadBalancer loadBalancer, String backendName)
  type: Method
  summary: <p>Specifies the load balancer backend to associate this IP configuration with. </p>
  syntax:
    content: public WithAttach< ParentT > withExistingLoadBalancerBackend(LoadBalancer loadBalancer, String backendName)
    parameters:
    - id: loadBalancer
      type: com.microsoft.azure.management.network._load_balancer
      description: <p>an existing load balancer </p>
    - id: backendName
      type: "26831127"
      description: <p>the name of an existing backend on that load balancer </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_attacha6da57ba
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definit7752274ae53ec6c93861035156ab069e.withExistingLoadBalancerInboundNatRule(LoadBalancer,String)
  parent: com.microsoft.azure.management.network._nic_ip_configuration._definit7752274ae53ec6c93861035156ab069e
  href: com.microsoft.azure.management.network._nic_ip_configuration._definit7752274ae53ec6c93861035156ab069e.yml
  name: withExistingLoadBalancerInboundNatRule(LoadBalancer loadBalancer, String inboundNatRuleName)
  fullName: WithAttach<ParentT> com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithLoadBalancer< ParentT >.withExistingLoadBalancerInboundNatRule(LoadBalancer loadBalancer, String inboundNatRuleName)
  type: Method
  summary: <p>Specifies the load balancer inbound NAT rule to associate this IP configuration with. </p>
  syntax:
    content: public WithAttach< ParentT > withExistingLoadBalancerInboundNatRule(LoadBalancer loadBalancer, String inboundNatRuleName)
    parameters:
    - id: loadBalancer
      type: com.microsoft.azure.management.network._load_balancer
      description: <p>an existing load balancer </p>
    - id: inboundNatRuleName
      type: "26831127"
      description: <p>the name of an existing inbound NAT rule on the selected load balancer </p>
    return:
      type: com.microsoft.azure.management.network._nic_ip_configuration._definition_stages._with_attacha6da57ba
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition
  parent: com.microsoft.azure.management.resources.fluentcore.model
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable._in_definition.yml
  name: Attachable.InDefinition<ParentT>
  fullName: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InDefinition<ParentT>
  type: Interface
  summary: <p>The final stage of the child object definition, as which it can be attached to the parent. </p>
  syntax:
    content: public interface InDefinition<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the parent definition </p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definit33306d6d391c9abb4aee8d314a017df9
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definit33306d6d391c9abb4aee8d314a017df9.yml
  name: NicIpConfiguration.DefinitionStages.WithPublicIpAddress<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithPublicIpAddress<ParentT>
  type: Interface
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to associate it with a public IP address.</p>

    <p></p>
  syntax:
    content: public interface WithPublicIpAddress<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definit7752274ae53ec6c93861035156ab069e
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definit7752274ae53ec6c93861035156ab069e.yml
  name: NicIpConfiguration.DefinitionStages.WithLoadBalancer<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.DefinitionStages.WithLoadBalancer<ParentT>
  type: Interface
  summary: >-
    <p>The stage of the network interface IP configuration definition allowing to specify the load balancer to associate this IP configuration with.</p>

    <p></p>
  syntax:
    content: public interface WithLoadBalancer<ParentT>
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.network._nic_ip_configuration._definition
  parent: com.microsoft.azure.management.network
  href: com.microsoft.azure.management.network._nic_ip_configuration._definition.yml
  name: NicIpConfiguration.Definition<ParentT>
  fullName: com.microsoft.azure.management.network.NicIpConfiguration.Definition<ParentT>
  type: Interface
  summary: <p>The entirety of the network interface IP configuration definition. </p>
  syntax:
    content: public interface Definition<ParentT> extends NicIpConfiguration.DefinitionStages.Blank< ParentT >,NicIpConfiguration.DefinitionStages.WithAttach< ParentT >,NicIpConfiguration.DefinitionStages.WithNetwork< ParentT >,NicIpConfiguration.DefinitionStages.WithSubnet< ParentT >,NicIpConfiguration.DefinitionStages.WithPrivateIp< ParentT >
    typeParameters:
    - type: 18a275b1
      description: <p>the return type of the final <xref href="com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()" data-throw-if-not-resolved="false"></xref></p>
- uid: com.microsoft.azure.management.resources.fluentcore.model._attachable.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model._attachable
  href: com.microsoft.azure.management.resources.fluentcore.model._attachable.yml
  name: attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable< ParentT >.attach()
  type: Method
  summary: <p>Attaches this child object's definition to its parent's definition. </p>
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent object's definition </p>
