items:
- uid: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
  id: _application_gateway_url_path_map_inner
  parent: com.microsoft.azure.management.network.implementation
  children:
  - com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.defaultBackendAddressPool()
  - com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.defaultBackendHttpSettings()
  - com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.etag()
  - com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.name()
  - com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.pathRules()
  - com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.provisioningState()
  - com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.withDefaultBackendAddressPool(SubResource)
  - com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.withDefaultBackendHttpSettings(SubResource)
  - com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.withEtag(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.withName(String)
  - com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.withPathRules(List< ApplicationGatewayPathRuleInner >)
  - com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.withProvisioningState(String)
  href: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.yml
  langs:
  - java
  name: ApplicationGatewayUrlPathMapInner
  fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewayUrlPathMapInner
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayUrlPathMapInner.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayUrlPathMapInner.java
    startLine: 19
  package: com.microsoft.azure.management.network.implementation
  summary: <p>UrlPathMap of application gateway. </p>
  syntax: &o1
    content: public class ApplicationGatewayUrlPathMapInner
  inheritance:
  - java.lang.Object
  - SubResource
- uid: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.defaultBackendAddressPool()
  id: defaultBackendAddressPool()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.yml
  langs:
  - java
  name: defaultBackendAddressPool()
  fullName: SubResource com.microsoft.azure.management.network.implementation.ApplicationGatewayUrlPathMapInner.defaultBackendAddressPool()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayUrlPathMapInner.java
    startLine: 61
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the defaultBackendAddressPool value.</p>

    <p></p>
  syntax:
    content: public SubResource defaultBackendAddressPool()
    return:
      type: 4151c390
      description: <p>the defaultBackendAddressPool value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.defaultBackendHttpSettings()
  id: defaultBackendHttpSettings()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.yml
  langs:
  - java
  name: defaultBackendHttpSettings()
  fullName: SubResource com.microsoft.azure.management.network.implementation.ApplicationGatewayUrlPathMapInner.defaultBackendHttpSettings()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayUrlPathMapInner.java
    startLine: 81
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the defaultBackendHttpSettings value.</p>

    <p></p>
  syntax:
    content: public SubResource defaultBackendHttpSettings()
    return:
      type: 4151c390
      description: <p>the defaultBackendHttpSettings value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.etag()
  id: etag()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.yml
  langs:
  - java
  name: etag()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayUrlPathMapInner.etag()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayUrlPathMapInner.java
    startLine: 161
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the etag value.</p>

    <p></p>
  syntax:
    content: public String etag()
    return:
      type: "26831127"
      description: <p>the etag value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.name()
  id: name()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.yml
  langs:
  - java
  name: name()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayUrlPathMapInner.name()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayUrlPathMapInner.java
    startLine: 141
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the name value.</p>

    <p></p>
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.pathRules()
  id: pathRules()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.yml
  langs:
  - java
  name: pathRules()
  fullName: List<ApplicationGatewayPathRuleInner> com.microsoft.azure.management.network.implementation.ApplicationGatewayUrlPathMapInner.pathRules()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayUrlPathMapInner.java
    startLine: 101
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the pathRules value.</p>

    <p></p>
  syntax:
    content: public List< ApplicationGatewayPathRuleInner > pathRules()
    return:
      type: f6a6204dcom.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner9ec3e006
      description: <p>the pathRules value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.provisioningState()
  id: provisioningState()
  parent: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.yml
  langs:
  - java
  name: provisioningState()
  fullName: String com.microsoft.azure.management.network.implementation.ApplicationGatewayUrlPathMapInner.provisioningState()
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayUrlPathMapInner.java
    startLine: 121
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Get the provisioningState value.</p>

    <p></p>
  syntax:
    content: public String provisioningState()
    return:
      type: "26831127"
      description: <p>the provisioningState value </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.withDefaultBackendAddressPool(SubResource)
  id: withDefaultBackendAddressPool(SubResource)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.yml
  langs:
  - java
  name: withDefaultBackendAddressPool(SubResource defaultBackendAddressPool)
  fullName: ApplicationGatewayUrlPathMapInner com.microsoft.azure.management.network.implementation.ApplicationGatewayUrlPathMapInner.withDefaultBackendAddressPool(SubResource defaultBackendAddressPool)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayUrlPathMapInner.java
    startLine: 71
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the defaultBackendAddressPool value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayUrlPathMapInner withDefaultBackendAddressPool(SubResource defaultBackendAddressPool)
    parameters:
    - id: defaultBackendAddressPool
      type: 4151c390
      description: <p>the defaultBackendAddressPool value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.withDefaultBackendHttpSettings(SubResource)
  id: withDefaultBackendHttpSettings(SubResource)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.yml
  langs:
  - java
  name: withDefaultBackendHttpSettings(SubResource defaultBackendHttpSettings)
  fullName: ApplicationGatewayUrlPathMapInner com.microsoft.azure.management.network.implementation.ApplicationGatewayUrlPathMapInner.withDefaultBackendHttpSettings(SubResource defaultBackendHttpSettings)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayUrlPathMapInner.java
    startLine: 91
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the defaultBackendHttpSettings value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayUrlPathMapInner withDefaultBackendHttpSettings(SubResource defaultBackendHttpSettings)
    parameters:
    - id: defaultBackendHttpSettings
      type: 4151c390
      description: <p>the defaultBackendHttpSettings value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.withEtag(String)
  id: withEtag(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.yml
  langs:
  - java
  name: withEtag(String etag)
  fullName: ApplicationGatewayUrlPathMapInner com.microsoft.azure.management.network.implementation.ApplicationGatewayUrlPathMapInner.withEtag(String etag)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayUrlPathMapInner.java
    startLine: 171
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the etag value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayUrlPathMapInner withEtag(String etag)
    parameters:
    - id: etag
      type: "26831127"
      description: <p>the etag value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.withName(String)
  id: withName(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.yml
  langs:
  - java
  name: withName(String name)
  fullName: ApplicationGatewayUrlPathMapInner com.microsoft.azure.management.network.implementation.ApplicationGatewayUrlPathMapInner.withName(String name)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayUrlPathMapInner.java
    startLine: 151
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the name value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayUrlPathMapInner withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.withPathRules(List< ApplicationGatewayPathRuleInner >)
  id: withPathRules(List< ApplicationGatewayPathRuleInner >)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.yml
  langs:
  - java
  name: withPathRules(List< ApplicationGatewayPathRuleInner > pathRules)
  fullName: ApplicationGatewayUrlPathMapInner com.microsoft.azure.management.network.implementation.ApplicationGatewayUrlPathMapInner.withPathRules(List< ApplicationGatewayPathRuleInner > pathRules)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayUrlPathMapInner.java
    startLine: 111
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the pathRules value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayUrlPathMapInner withPathRules(List< ApplicationGatewayPathRuleInner > pathRules)
    parameters:
    - id: pathRules
      type: f6a6204dcom.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner9ec3e006
      description: <p>the pathRules value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
- uid: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.withProvisioningState(String)
  id: withProvisioningState(String)
  parent: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
  href: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.yml
  langs:
  - java
  name: withProvisioningState(String provisioningState)
  fullName: ApplicationGatewayUrlPathMapInner com.microsoft.azure.management.network.implementation.ApplicationGatewayUrlPathMapInner.withProvisioningState(String provisioningState)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayUrlPathMapInner.java
    startLine: 131
  package: com.microsoft.azure.management.network.implementation
  summary: >-
    <p>Set the provisioningState value.</p>

    <p></p>
  syntax:
    content: public ApplicationGatewayUrlPathMapInner withProvisioningState(String provisioningState)
    parameters:
    - id: provisioningState
      type: "26831127"
      description: <p>the provisioningState value to set </p>
    return:
      type: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
      description: <p>the <xref href="com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner" data-throw-if-not-resolved="false"></xref> object itself. </p>
references:
- uid: 4151c390
  spec.java:
  - name: SubResource
    fullName: SubResource
- uid: f6a6204dcom.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner9ec3e006
  spec.java:
  - name: 'List< '
    fullName: 'List< '
  - uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
    name: ApplicationGatewayPathRuleInner
    fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner
    href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  - name: " >"
    fullName: " >"
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner
  parent: com.microsoft.azure.management.network.implementation
  href: com.microsoft.azure.management.network.implementation._application_gateway_path_rule_inner.yml
  name: ApplicationGatewayPathRuleInner
  fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewayPathRuleInner
  type: Class
  summary: <p>Path rule of URL path map of application gateway. </p>
  syntax:
    content: public class ApplicationGatewayPathRuleInner
- uid: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner
  parent: com.microsoft.azure.management.network.implementation
  href: com.microsoft.azure.management.network.implementation._application_gateway_url_path_map_inner.yml
  name: ApplicationGatewayUrlPathMapInner
  fullName: com.microsoft.azure.management.network.implementation.ApplicationGatewayUrlPathMapInner
  type: Class
  summary: <p>UrlPathMap of application gateway. </p>
  syntax: *o1
