items:
- uid: com.microsoft.azure.management.batch._application._update_stages._with_optional_properties
  id: _with_optional_properties
  parent: com.microsoft.azure.management.batch
  children:
  - com.microsoft.azure.management.batch._application._update_stages._with_optional_properties.withAllowUpdates(boolean)
  - com.microsoft.azure.management.batch._application._update_stages._with_optional_properties.withDisplayName(String)
  href: com.microsoft.azure.management.batch._application._update_stages._with_optional_properties.yml
  langs:
  - java
  name: Application.UpdateStages.WithOptionalProperties
  fullName: com.microsoft.azure.management.batch.Application.UpdateStages.WithOptionalProperties
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 208
  package: com.microsoft.azure.management.batch
  summary: <p>The stage of the application update allowing to enable or disable auto upgrade of the application. </p>
  syntax:
    content: public interface WithOptionalProperties
- uid: com.microsoft.azure.management.batch._application._update_stages._with_optional_properties.withAllowUpdates(boolean)
  id: withAllowUpdates(boolean)
  parent: com.microsoft.azure.management.batch._application._update_stages._with_optional_properties
  href: com.microsoft.azure.management.batch._application._update_stages._with_optional_properties.yml
  langs:
  - java
  name: withAllowUpdates(boolean allowUpdates)
  fullName: Update com.microsoft.azure.management.batch.Application.UpdateStages.WithOptionalProperties.withAllowUpdates(boolean allowUpdates)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 215
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Allow automatic application updates.</p>

    <p></p>
  syntax:
    content: public Update withAllowUpdates(boolean allowUpdates)
    parameters:
    - id: allowUpdates
      type: 4fc6e284
      description: <p>true to allow the automatic updates of application, otherwise false </p>
    return:
      type: com.microsoft.azure.management.batch._application._update
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.batch._application._update_stages._with_optional_properties.withDisplayName(String)
  id: withDisplayName(String)
  parent: com.microsoft.azure.management.batch._application._update_stages._with_optional_properties
  href: com.microsoft.azure.management.batch._application._update_stages._with_optional_properties.yml
  langs:
  - java
  name: withDisplayName(String displayName)
  fullName: Update com.microsoft.azure.management.batch.Application.UpdateStages.WithOptionalProperties.withDisplayName(String displayName)
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/Application.java
    startLine: 223
  package: com.microsoft.azure.management.batch
  summary: >-
    <p>Specifies the display name for the application.</p>

    <p></p>
  syntax:
    content: public Update withDisplayName(String displayName)
    parameters:
    - id: displayName
      type: "26831127"
      description: <p>the displayName value to set </p>
    return:
      type: com.microsoft.azure.management.batch._application._update
      description: <p>the next stage of the update </p>
references:
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.batch._application._update
  parent: com.microsoft.azure.management.batch
  href: com.microsoft.azure.management.batch._application._update.yml
  name: Application.Update
  fullName: com.microsoft.azure.management.batch.Application.Update
  type: Interface
  summary: <p>The entirety of application update as a part of parent batch account update. </p>
  syntax:
    content: public interface Update extends Settable< BatchAccount.Update >,Application.UpdateStages.WithOptionalProperties,Application.UpdateStages.WithApplicationPackage
- uid: com.microsoft.azure.management.batch.implementation._application_impl.withAllowUpdates(boolean)
  parent: com.microsoft.azure.management.batch.implementation._application_impl
  href: com.microsoft.azure.management.batch.implementation._application_impl.yml
  name: withAllowUpdates(boolean allowUpdates)
  fullName: ApplicationImpl com.microsoft.azure.management.batch.implementation.ApplicationImpl.withAllowUpdates(boolean allowUpdates)
  type: Method
  summary: >-
    <p>Allow automatic application updates.</p>

    <p></p>
  syntax:
    content: public ApplicationImpl withAllowUpdates(boolean allowUpdates)
    parameters:
    - id: allowUpdates
      type: 4fc6e284
      description: <p>true to allow the automatic updates of application, otherwise false </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._application_impl
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.batch.implementation._application_impl.withDisplayName(String)
  parent: com.microsoft.azure.management.batch.implementation._application_impl
  href: com.microsoft.azure.management.batch.implementation._application_impl.yml
  name: withDisplayName(String displayName)
  fullName: ApplicationImpl com.microsoft.azure.management.batch.implementation.ApplicationImpl.withDisplayName(String displayName)
  type: Method
  summary: >-
    <p>Specifies the display name for the application.</p>

    <p></p>
  syntax:
    content: public ApplicationImpl withDisplayName(String displayName)
    parameters:
    - id: displayName
      type: "26831127"
      description: <p>the displayName value to set </p>
    return:
      type: com.microsoft.azure.management.batch.implementation._application_impl
      description: <p>the next stage of the update </p>
